// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Geolocation: typeof import('./components/Geolocation.vue')['default']
    GMap: typeof import('./components/GMap.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconMoon: typeof import('./components/IconMoon.vue')['default']
    IconSun: typeof import('./components/IconSun.vue')['default']
    OpeningTimes: typeof import('./components/OpeningTimes.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Station: typeof import('./components/Station.vue')['default']
    Stations: typeof import('./components/Stations.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
  }
}

export {}
